use crate::config::Config;
use anyhow::{Context, Result, bail};
use std::{
    fs,
    path::{Path, PathBuf},
};

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}
fn executable(name: &str, root: &Path) -> Result<PathBuf> {
    let path = std::env::var_os("PATH").unwrap_or_default();
    for directory in std::env::split_paths(&path) {
        if directory == root.join("bin") {
            continue;
        }
        let candidate = directory.join(name);
        if candidate.is_file() {
            return Ok(candidate.canonicalize()?);
        }
    }
    bail!("{name} is not installed or not on PATH")
}
pub fn connect(agent: &str, root: &Path, config: &Config) -> Result<Option<PathBuf>> {
    let (name, kind) = match agent {
        "claude-code" => ("claude", "claude"),
        "codex" => ("codex", "codex"),
        _ => return Ok(None),
    };
    let real = executable(name, root)?;
    fs::create_dir_all(root.join("bin"))?;
    let wrapper = root.join("bin").join(name);
    if wrapper.exists()
        && !fs::read_to_string(&wrapper)?.starts_with("#!/bin/sh\n# Generated by ctx\n")
    {
        bail!("refusing to replace existing {}", wrapper.display());
    }
    let model = config
        .model
        .as_ref()
        .map(|m| m.model.as_str())
        .unwrap_or("");
    let base = format!("http://127.0.0.1:{}/a/{agent}", config.port);
    let ctx_binary = if std::env::var_os("CTX_HOME").is_some() {
        std::env::current_exe()?
    } else {
        root.join("bin/ctx")
    };
    let mcp_config = root.join("bin/ctx-mcp.json");
    fs::write(
        &mcp_config,
        serde_json::to_vec_pretty(
            &serde_json::json!({"mcpServers":{"ctx":{"command":ctx_binary,"args":["mcp"]}}}),
        )?,
    )?;
    let codex_mcp = format!(
        "mcp_servers.ctx={{command={},args=[\"mcp\"]}}",
        serde_json::to_string(&ctx_binary.display().to_string())?
    );
    let prefix = format!(
        "#!/bin/sh\n# Generated by ctx\nCTX_ROOT={}\nCTX_REAL={}\nCTX_BASE={}\nCTX_MODEL={}\nCTX_PORT={}\nCTX_MCP={}\nCTX_CODEX_MCP={}\nCTX_TOKEN=$(cat \"$CTX_ROOT/token\")\n",
        shell_quote(&root.display().to_string()),
        shell_quote(&real.display().to_string()),
        shell_quote(&base),
        shell_quote(model),
        config.port,
        shell_quote(&mcp_config.display().to_string()),
        shell_quote(&codex_mcp),
    );
    let script = if kind == "claude" {
        format!(
            "{prefix}if ! curl --silent --fail --max-time 0.3 -H \"X-Ctx-Token: $CTX_TOKEN\" \"http://127.0.0.1:$CTX_PORT/api/v1/health\" >/dev/null 2>&1; then\n  exec \"$CTX_REAL\" --mcp-config \"$CTX_MCP\" \"$@\"\nfi\nexport ANTHROPIC_BASE_URL=\"$CTX_BASE\"\nexport ANTHROPIC_API_KEY=\"$CTX_TOKEN\"\nif [ -n \"$CTX_MODEL\" ]; then\n  exec \"$CTX_REAL\" --mcp-config \"$CTX_MCP\" --model \"$CTX_MODEL\" \"$@\"\nfi\nexec \"$CTX_REAL\" --mcp-config \"$CTX_MCP\" \"$@\"\n"
        )
    } else {
        let provider = format!(
            "model_providers.ctx={{name=\"ctx\",base_url={},auth={{command=\"/bin/cat\",args=[{}]}}}}",
            serde_json::to_string(&format!("{base}/v1"))?,
            serde_json::to_string(&root.join("token").display().to_string())?
        );
        format!(
            "{prefix}CTX_PROVIDER={}\nif ! curl --silent --fail --max-time 0.3 -H \"X-Ctx-Token: $CTX_TOKEN\" \"http://127.0.0.1:$CTX_PORT/api/v1/health\" >/dev/null 2>&1; then\n  exec \"$CTX_REAL\" -c \"$CTX_CODEX_MCP\" \"$@\"\nfi\nif [ -n \"$CTX_MODEL\" ]; then\n  exec \"$CTX_REAL\" -c \"$CTX_CODEX_MCP\" -c model_provider=ctx -c \"$CTX_PROVIDER\" -m \"$CTX_MODEL\" \"$@\"\nfi\nexec \"$CTX_REAL\" -c \"$CTX_CODEX_MCP\" -c model_provider=ctx -c \"$CTX_PROVIDER\" \"$@\"\n",
            shell_quote(&provider)
        )
    };
    fs::write(&wrapper, script)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&wrapper, fs::Permissions::from_mode(0o700))?;
    }
    if std::env::var_os("CTX_HOME").is_none() {
        add_path_to_shell(root)?;
    }
    Ok(Some(wrapper))
}
pub fn disconnect(agent: &str, root: &Path) -> Result<()> {
    let name = match agent {
        "claude-code" => "claude",
        "codex" => "codex",
        _ => return Ok(()),
    };
    let path = root.join("bin").join(name);
    if path.exists() && fs::read_to_string(&path)?.starts_with("#!/bin/sh\n# Generated by ctx\n") {
        fs::remove_file(path)?;
    }
    Ok(())
}
fn add_path_to_shell(root: &Path) -> Result<()> {
    let profile = PathBuf::from(std::env::var_os("HOME").context("HOME missing")?).join(".zshrc");
    let original = fs::read_to_string(&profile).unwrap_or_default();
    let marker = "# ctx runtime PATH";
    if original.contains(marker) {
        return Ok(());
    }
    let backup = root.join("backups");
    fs::create_dir_all(&backup)?;
    if profile.exists() {
        fs::copy(
            &profile,
            backup.join(format!("zshrc-{}", chrono::Utc::now().timestamp())),
        )?;
    }
    let mut updated = original;
    if !updated.is_empty() && !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str(&format!(
        "{marker}\nexport PATH={}:$PATH\n",
        shell_quote(&root.join("bin").display().to_string())
    ));
    fs::write(profile, updated)?;
    Ok(())
}
pub fn ensure_service(root: &Path) -> Result<()> {
    if std::env::var_os("CTX_HOME").is_some() {
        return Ok(());
    }
    #[cfg(target_os = "macos")]
    {
        let exe = std::env::current_exe()?;
        fs::create_dir_all(root.join("bin"))?;
        let installed = root.join("bin/ctx");
        if exe != installed {
            let temp = root.join("bin/ctx.new");
            fs::copy(&exe, &temp)?;
            fs::rename(temp, &installed)?;
        }
        let launch_dir = PathBuf::from(std::env::var_os("HOME").context("HOME missing")?)
            .join("Library/LaunchAgents");
        fs::create_dir_all(&launch_dir)?;
        let plist = launch_dir.join("dev.ctx.runtime.plist");
        let xml = format!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"><plist version=\"1.0\"><dict><key>Label</key><string>dev.ctx.runtime</string><key>ProgramArguments</key><array><string>{}</string><string>serve</string></array><key>RunAtLoad</key><true/><key>KeepAlive</key><true/><key>StandardOutPath</key><string>{}</string><key>StandardErrorPath</key><string>{}</string></dict></plist>",
            xml_escape(&installed.display().to_string()),
            xml_escape(&root.join("ctxd.out.log").display().to_string()),
            xml_escape(&root.join("ctxd.err.log").display().to_string())
        );
        fs::write(&plist, xml)?;
        let uid = std::process::Command::new("id").arg("-u").output()?;
        let domain = format!("gui/{}", String::from_utf8(uid.stdout)?.trim());
        let service = format!("{domain}/dev.ctx.runtime");
        let loaded = std::process::Command::new("launchctl")
            .args(["print", &service])
            .output()?
            .status
            .success();
        if !loaded {
            let status = std::process::Command::new("launchctl")
                .args(["bootstrap", &domain])
                .arg(&plist)
                .status()?;
            if !status.success() {
                bail!("launchd could not register ctx daemon");
            }
        }
        let status = std::process::Command::new("launchctl")
            .args(["kickstart", "-k", &service])
            .status()?;
        if !status.success() {
            bail!("launchd could not start ctx daemon");
        }
    }
    Ok(())
}
#[cfg(target_os = "macos")]
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn safe_shell_quoting() {
        assert_eq!(shell_quote("a'b"), "'a'\\''b'");
    }
}
